version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: airbnb-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Admin@123
      - MSSQL_PID=Express
      - MSSQL_TCP_PORT=1433
      # Minimum memory requirement for SQL Server
      - MSSQL_MEMORY_LIMIT_MB=1024
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    restart: unless-stopped
    networks:
      - airbnb-network
    # Use the default SQL Server startup (no additional tools needed for API)

  api:
    build:
      context: .
      dockerfile: Dockerfile.new-schema
    container_name: airbnb-api
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=development
      - PORT=3004
      - DB_USER=sa
      - DB_PASSWORD=Admin@123
      - DB_HOST=sqlserver
      - DB_NAME=airbnb
      - DB_PORT=1433
      - JWT_SECRET=your_jwt_secret_key_here
      - BASE_URL=http://localhost:3004
      # Add longer timeouts for SQL Server connections
      - MSSQL_CONNECTION_TIMEOUT=60000
      - MSSQL_REQUEST_TIMEOUT=60000
      # Use the new schema
      - USE_NEW_SCHEMA=true
    depends_on:
      - sqlserver
    restart: unless-stopped
    networks:
      - airbnb-network
    volumes:
      # Mount the uploads directory for profile images and property images
      - ./public/uploads:/app/public/uploads
    # Use a more robust startup script with the new schema
    command: >
      sh -c "
        echo 'Waiting for SQL Server to be ready...' &&
        for i in {1..30}; do
          if nc -z sqlserver 1433; then
            echo 'SQL Server is accepting connections!'
            break
          fi
          echo 'Waiting for SQL Server to start...'
          sleep 5
        done &&
        sleep 10 &&
        echo 'Initializing database with new schema...' &&
        node src/models/reset-db.js &&
        echo 'Starting application...' &&
        npm run dev
      "

volumes:
  sqlserver-data:
    name: airbnb-sqlserver-data-new-schema

networks:
  airbnb-network:
    driver: bridge
    name: airbnb-network-new-schema
